apiVersion: v1
kind: Service
metadata:
  name: nginx-web-service
  namespace: fluxdemo
spec:
  selector:
    app: nginx-web
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80